#!/usr/bin/env bash
# generates a MySQL dump and creates a compressed archive out of it

day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
files="$day-$month-$year.tar.gz"

mysqldump --all-databases -u root --password="$1" > backup.sql
tar -czvf "$files" backup.sql
