#!/usr/bin/env bash
# generates a MySQL dump and creates a compressed archive out of it

day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
file="$day-$month-$year.tar.gz"
mysqldump --al-databases -u root --password="$1" > backup.sql
tar -czvf "$file" backup.sql
