#!/usr/bin/env bash
# Configure the NGINX server to listen on port 80

# 1. create a symbolic link between the 
# Nginx config file and the enabled sites directory
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# 2. restart nginx 
service nginx start

# end the first nginx process
kill "$(pgrep 'nginx' | head -l)"
