#!/usr/bin/env bash
# A script that
# To infinity and beyond indefinitely
# With a sleep 2 in between each iteration
# I am invincible!!! when receiving a SIGTERM signal

# Infinite loop displaying the message with 2 sec sleep
while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invicible!!!"' SIGTERM
done
