#!/usr/bin/env bash
# script that displays the content of the file /etc/passwd

# use while loop to read each line
while IFS=':' read -r username _ uid _ home _; do
	echo "$username:$uid:$home"
done < /etc/passwd
