#!/usr/bin/env bash
# print "Best School" 10 times use a while loop

# initialize a counter
count=0;

# iterate to display "Best School"
while (("$count" <= 10)); do
	echo "Best School"
	((count++))
done
