#!/usr/bin/env bash
# This script provides information about the school file

path_file="school"

#check if the file exists
if [ -e "$path_file" ]; then
	echo "school file exists"

	# check if the file is empty
	if [ -s "$path_file" ]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	# check if the file is a regular file
	if [ -f "$path_file" ]; then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
