#!usr/bin/env bash
# Configure ufw so that it blocks all incoming traffic, except the following TCP ports: 22(ssh), 443(https ssl), 80(http)

sudo apt install ufw
sudo ufw default allow outgoing
sudo ufw default deny incomung
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
sudo ufw status
